apiVersion: v1
kind: Service
metadata:
  name: softarch-assignment-7
spec:
  selector:
      pod: softarch-assignment-7
  ports:
    - protocol: TCP
      port: 8080       # The port, the service listens on.
      targetPort: 80   # The port, the traffic is sent to on the Pod.
  type: LoadBalancer
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softarch-assignment-7
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: softarch-assignment-7
  template:
    metadata:
      labels:
        pod: softarch-assignment-7
    spec:
      containers:
        - name: softarch-assignment-7
          image: FreeSpirit0/softarch-assignment-7
